coverage:
  round: nearest
ignore:
  - "schemacrawler-testdb"  # ignore folders and all its contents
  - "schemacrawler-diff"  # ignore folders and all its contents
  - "schemacrawler-examplecode"  # ignore folders and all its contents
