version: '3.7'

services:

  cassandra:
    image: cassandra
    container_name: cassandra
    ports:
      - target: 9042
        published: 9042
        protocol: tcp
        mode: host
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5
