version: '3.7'

services:

  db2:
    image: ibmcom/db2:11.5.0.0a
    ports:
      - target: 50000
        published: 50000
        protocol: tcp
        mode: host
    privileged: true
    environment:
      LICENSE: accept
      ARCHIVE_LOGS: "false"
      AUTOCONFIG: "false"
      DBNAME: schcrwlr
      DB2INSTANCE: schcrwlr
      DB2INST1_PASSWORD: schemacrawler
    # command: su - db2inst1 -c "db2start; db2 CREATE DATABASE BOOKS"
