services:

  db2:
    image: icr.io/db2_community/db2:11.5.9.0
    container_name: db2
    ports:
      - target: 50000
        published: 50000
        protocol: tcp
        mode: host
    privileged: true
    environment:
      LICENSE: accept
      DB2INSTANCE: schcrwlr
      DB2INST1_PASSWORD: schemacrawler
      DBNAME: schcrwlr
      ARCHIVE_LOGS: false
      AUTOCONFIG: false
      TO_CREATE_SAMPLEDB: true
      REPODB: false
