version: '3.7'

services:

  oracle:
    image: store/oracle/database-enterprise:12.2.0.1-slim
    container_name: oracle
    ports:
      - target: 1521
        published: 1521
        protocol: tcp
        mode: host      
