version: '3.7'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-CU26-ubuntu-16.04
    container_name: sqlserver
    ports:
      - target: 1433
        published: 1433
        protocol: tcp
        mode: host
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Schem#Crawl3r
