name: Feature Request
description: Suggest an idea for this project
labels: 
  - enhancement
assignees:
  - sualeh
body:
  - type: textarea
    id: feature-request-description
    attributes:
      label: Feature Request
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: feature-request-alternatives
    attributes:
      label: Possible Alternatives
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: feature-request-additional-context
    attributes:
      label: Additional Context
      description: Additional context
      placeholder: Add any other context or screenshots about the feature request here.
    validations:
      required: false
