name: Database Integration Tests

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  schedule:
    - cron: '21 21 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  build:
    name: Database Integration Tests
    strategy:
      fail-fast: false
      matrix:
        database: [oracle, sqlserver, postgresql, mysql, db2]
    runs-on: ubuntu-latest
    steps:

# SETUP BUILD ENVIRONMENT
    - id: prepare-maven-build
      name: Prepare Maven build
      uses: sualeh/prepare-maven-build@v1.3.5
      with:
        java-version: 8
    - id: install-graphviz
      name: Install Graphviz
      uses: sualeh/install-graphviz@v1.0.3
    - id: maximize-build-space
      name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: '3072'
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'

# RUN DATABASE TESTS
    - id: build-test-databases
      name: Build and run database tests
      shell: bash
      run: |
        # Build
        du -sh /var/lib/docker
        if [ "${{ matrix.database }}" == "oracle" ]; then
            docker pull gvenzl/oracle-xe:21-slim-faststart
        elif [ "${{ matrix.database }}" == "sqlserver" ]; then
            docker pull mcr.microsoft.com/mssql/server:2019-CU9-ubuntu-18.04
        elif [ "${{ matrix.database }}" == "db2" ]; then
            docker pull ibmcom/db2
        fi
        mvn \
          --no-transfer-progress \
          --batch-mode \
          -D${{ matrix.database }} \
          --projects schemacrawler-${{ matrix.database }} \
          --also-make \
          clean package
        # Save expected results files
        .github/scripts/unit-tests-results-output.sh
    - id: upload-unit-tests-results-output
      name: Upload expected results files
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: unit-tests-results-output
        path: ./unit-tests-results-output.zip
        retention-days: 5
