name: Compare Database Schema Outputs

on:
  workflow_dispatch:

jobs:
  diff-output:
    runs-on: ubuntu-latest

    steps:
    - id: setup-node
      uses: actions/setup-node@v4
      with:
        node-version: latest

    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v4

    - id: install-diff2html
      name: Install diff2html
      shell: bash
      run: |
        # Install diff2html-cli
        npm config set fund false
        npm --version
        diff --version
        npm install -g diff2html-cli
        diff2html --version

    - id: generate-diff
      name: Compare files and generate diff
      shell: sh
      run: |
        # Generate diff in HTML
        #
        mkdir --verbose diff-output/
        ./.github/scripts/diff-output.sh \
          schemacrawler-oracle/src/test/resources/testOraclePortable.txt \
          schemacrawler-sqlserver/src/test/resources/testSQLServerPortable.txt \
          ./diff-output/oracle-sqlserver.html \
          "Oracle - SQL Server"
        #
        mkdir --verbose diff-output/
        ./.github/scripts/diff-output.sh \
          schemacrawler-oracle/src/test/resources/testOraclePortable.txt \
          schemacrawler-oracle/src/test/resources/testOracleWithConnection.8.txt \
          ./diff-output/oracle-portable-standard.html \
          "Oracle - Portable versus Standard"
        #
        mkdir --verbose diff-output/
        ./.github/scripts/diff-output.sh \
          schemacrawler-sqlserver/src/test/resources/testSQLServerPortable.txt \
          schemacrawler-sqlserver/src/test/resources/testSQLServerWithConnection.8.txt \
          ./diff-output/sqlserver-portable-standard.html \
          "SQL Server - Portable versus Standard"

    - id: upload-diff-output
      name: Upload diff-output
      uses: actions/upload-artifact@v4
      with:
        name: diff-output
        path: ./diff-output/
        retention-days: 5
