name: Integration Tests

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build, run database integration tests, and publish results
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        # (MacOS does not support Docker)
        java: [8, 17]
    runs-on: ${{ matrix.os }}
    steps:

# SETUP BUILD ENVIRONMENT
    - id: prepare-maven-build
      name: Prepare Maven build
      uses: sualeh/prepare-maven-build@v1.1.1
      with:
        java-version: ${{ matrix.java }}

# LINT CODE
    - id: lint-code-base
      name: Lint Code Base
      uses: github/super-linter/slim@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_ALL_CODEBASE: true
        VALIDATE_YAML: true
        VALIDATE_JSON: true
        VALIDATE_XML: true
        VALIDATE_MD: true
        VALIDATE_BASH: true
        # VALIDATE_PYTHON: false
        # VALIDATE_RUBY: false
        VALIDATE_JAVASCRIPT_ES: true
        VALIDATE_DOCKER: true
        VALIDATE_CSS: true
        VALIDATE_ENV: true
        VALIDATE_SQL: true

# BUILD AND TEST
    - id: build-test
      name: Build and run database integration tests
      env:
        TZ: GMT
      shell: bash
      run: |
        # Build
        mvn \
          --no-transfer-progress \
          --batch-mode \
          -Dtestcoverage \
          -Dlightdb \
          -Dheavydb \
          -Ddistrib \
          -Ddocker.skip=false \
          clean install \
          org.jacoco:jacoco-maven-plugin:0.8.7:report-aggregate

# GET TEST RESULTS
    - id: publish-test-results
      name: Upload results and coverage
      if: contains(github.ref, 'master')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: |
        # Upload results and coverage
        bash <(curl -s https://codecov.io/bash) -t 4456b669-238d-485f-a64a-250449710514
    - id: upload-coverage-test-results
      name: Upload coverage test results
      uses: actions/upload-artifact@v1
      with:
        name: coverage-test-results
        path: ./schemacrawler/target/site/jacoco-aggregate
