name: Integration Tests

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  schedule:
    - cron: '12 0/5 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  build:
    name: Integration Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [8, 17]
    runs-on: ${{ matrix.os }}
    steps:

# SETUP BUILD ENVIRONMENT
    - id: prepare-maven-build
      name: Prepare Maven build
      uses: sualeh/prepare-maven-build@v1.3.3
      with:
        java-version: ${{ matrix.java }}

# BUILD AND TEST
    - id: build-test
      name: Build and run database integration tests
      env:
        TZ: GMT
      shell: bash
      run: |
        # Build
        mvn \
          --no-transfer-progress \
          --batch-mode \
          -Dheavydb \
          -Ddistrib \
          clean package

# INSTALL GRAPHVIZ, AND RERUN DIAGRAM TESTS
    - id: install-graphviz
      name: Install Graphviz
      uses: sualeh/install-graphviz@v1.0.1
    - id: build-test-diagrams
      name: Build and run diagram tests
      shell: bash
      run: |
        # Build
        mvn \
          --no-transfer-progress \
          --batch-mode \
          --projects \
          schemacrawler-diagram,schemacrawler-scripting \
          --also-make \
          package


  build-test-docker:
    name: Build, run tests, and build Docker image
    runs-on: ubuntu-latest
    steps:

# SETUP BUILD ENVIRONMENT
    - id: prepare-maven-build
      name: Prepare Maven build
      uses: sualeh/prepare-maven-build@v1.3.3
      with:
        java-version: 8
    - id: install-graphviz
      name: Install Graphviz
      uses: sualeh/install-graphviz@v1.0.1

# BUILD AND TEST
    - id: build-test
      name: Build Docker image
      shell: bash
      run: |
        # Build
        mvn \
          --no-transfer-progress \
          --batch-mode \
          -Ddistrib \
          -Ddocker.skip=false \
          clean package
