name: Lint Code Base

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:

# SETUP BUILD ENVIRONMENT
    - id: prepare-maven-build
      name: Prepare Maven build
      uses: sualeh/prepare-maven-build@v1.2.0
      with:
        java-version: 8
    - id: install-packages
      name: Install packages
      shell: bash
      run: |
        # Install Graphviz
        sudo apt-get -qq update
        sudo apt-get -q install graphviz
        dot -V

# BUILD AND TEST
    - id: build-test
      name: Build all modules and run tests
      shell: bash
      run: |
        # Build
        mvn \
          --no-transfer-progress \
          --batch-mode \
          -Ddistrib \
          package

# LINT CODE
    - id: lint-code-base
      name: Lint Code Base
      uses: github/super-linter/slim@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_ALL_CODEBASE: true
        VALIDATE_YAML: true
        VALIDATE_JSON: true
        VALIDATE_XML: true
        VALIDATE_MD: true
        VALIDATE_BASH: true
        # VALIDATE_PYTHON: false
        # VALIDATE_RUBY: false
        VALIDATE_JAVASCRIPT_ES: true
        VALIDATE_DOCKER: true
        VALIDATE_CSS: true
        VALIDATE_ENV: true
        # VALIDATE_SQL: true

    - id: check-website-links
      name: Check website links
      uses: ruzickap/action-my-broken-link-checker@v1
      with:
        url: https://www.schemacrawler.com/
        pages_path: ./schemacrawler-website/target/_website
        cmd_params: "--skip-tls-verification --verbose --color=always"
        run_timeout: 10
        debug: true
