name: Database Integration Tests with Experimental Features

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  schedule:
    - cron: '12 0/2 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  build:
    name: Build, run single-threaded database integration tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [8, 17]
    steps:

# SETUP BUILD ENVIRONMENT
    - id: prepare-maven-build
      name: Prepare Maven build
      uses: sualeh/prepare-maven-build@v1.3.1
      with:
        java-version: ${{ matrix.java }}

    - id: install-graphviz
      name: Install graphviz
      shell: bash
      run: |
        # Install Graphviz
        sudo apt-get install graphviz
        dot -V

# BUILD AND TEST
    - id: build-test
      name: Build and run database integration tests
      env:
        TZ: GMT
        SC_SINGLE_THREADED: true
      shell: bash
      run: |
        # Build
        mvn \
          --no-transfer-progress \
          --batch-mode \
          -Dheavydb \
          clean package
